version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '80:3000'
    restart: always

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   environment:
  #     - NGROK_AUTHTOKEN=2fI31GclvD4ipuNK5jzFXSDFZEf_7zzD9rQy4KdgWts6eJe8B
  #   network_mode: host
  #   command: http 80
